#pragma once

#include <string_view>

// DO NOT EDIT !!!
// THIS FILE IS GENERATED BY CMAKE

namespace taraxa::cli {

constexpr std::string_view default_json = R"({
  "node_secret": "",
  "vrf_secret": "",
  "data_path": "",
  "network_listen_ip": "0.0.0.0",
  "network_tcp_port": 10002,
  "network_transaction_interval": 100,
  "network_ideal_peer_count": 5,
  "network_max_peer_count": 15,
  "network_sync_level_size": 25,
  "network_packets_processing_threads": 14,
  "network_peer_blacklist_timeout" : 600,
  "is_light_node" : false,
  "deep_syncing_threshold" : 10,
  "network_boot_nodes": [
  ],
  "rpc": {
    "http_port": 7777,
    "ws_port": 8777,
    "threads_num": 10
  },
  "max_transactions_pool_warn": 0,
  "max_transactions_pool_drop": 0,
  "max_block_queue_warn": 0,
  "db_config": {
    "db_snapshot_each_n_pbft_block": 10000,
    "db_max_snapshots": 5
  },
  "logging": {
    "configurations": [
      {
        "name": "standard",
        "on": true,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "SUMMARY",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "Taraxa_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "network",
        "on": false,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "PBFT_CHAIN",
            "verbosity": "INFO"
          },
          {
            "name": "PBFT_MGR",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "TARCAP",
            "verbosity": "DEBUG"
          },
          {
            "name": "NETWORK",
            "verbosity": "DEBUG"
          },
          {
            "name": "TRANSACTION_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAGBLKMGR",
            "verbosity": "INFO"
          },
          {
            "name": "DAGMGR",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "TaraxaNetwork_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "debug",
        "on": false,
        "verbosity": "DEBUG",
        "outputs": [
          {
            "type": "file",
            "file_name": "debug/TaraxaDebug_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      }
    ]
  },
  "chain_config": {
    "chain_id": "0x4",
    "dag_genesis_block": {
      "level": "0x0",
      "pivot": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "sig": "0xb7e22d46c1ba94d5e8347b01d137b5c428fcbbeaf0a77fb024cbbf1517656ff00d04f7f25be608c321b0d7483c402c294ff46c49b265305d046a52236c0a363701",
      "timestamp": "0x60aee104",
      "tips": [],
      "transactions": []
    },
    "final_chain": {
      "genesis_block_fields": {
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x60aee104"
      },
      "state": {
        "dpos": {
          "delegation_delay": "0x5",
          "delegation_locking_period": "0x5",
          "eligibility_balance_threshold": "0xd3c21bcecceda1000000",
          "vote_eligibility_balance_step": "0x152d02c7e14af6800000",
          "validator_maximum_stake":"0x84595161401484A000000",
          "minimum_deposit":"0x0",
          "commission_change_delta":"0x0",
          "commission_change_frequency":"0x0",
          "yield_percentage":"0x14",
          "initial_validators": [
            {
              "address": "0x780fe8b2226cf212c55635de399ee4c2a860810c",
              "owner": "0x780fe8b2226cf212c55635de399ee4c2a860810c",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa validator 1",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x56e0de6933d9d0453d0363caf42b136eb5854e4e",
              "owner": "0x56e0de6933d9d0453d0363caf42b136eb5854e4e",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa validator 2",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x71bdcbec7e3642782447b0fbf31eed068dfbdbb1",
              "owner": "0x71bdcbec7e3642782447b0fbf31eed068dfbdbb1",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa validator 3",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            }
          ]
        },
        "eth_chain_config": {
          "byzantium_block": "0x0",
          "constantinople_block": "0x0",
          "dao_fork_block": "0xffffffffffffffff",
          "eip_150_block": "0x0",
          "eip_158_block": "0x0",
          "homestead_block": "0x0",
          "petersburg_block": "0x0"
        },
        "execution_options": {
          "disable_nonce_check": false,
          "enable_nonce_skipping": true
        },
        "block_rewards_options": {
          "disable_block_rewards": false,
          "disable_contract_distribution": false
        },
        "genesis_balances": {
          "2cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9": "0x1027e72f1f12813088000000",
          "7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x1027e72f1f12813088000000"
        }
      }
    },
    "gas_price" : {
      "blocks" : 200,
      "percentile" : 60
    },
    "pbft": {
      "committee_size": "0x3e8",
      "number_of_proposers": "0x14",
      "dag_blocks_size": "0x32",
      "ghost_path_move_back": "0x0",
      "lambda_ms_min": "0x29a",
      "gas_limit": "0x3938700"
    },
    "dag": {
      "block_proposer": {
        "shard": 1,
        "transaction_limit": 250
      },
      "gas_limit": "0x989680"
    },
    "replay_protection_service": {
      "range": "0xa"
    },
    "sortition": {
      "changes_count_for_average": 10,
      "dag_efficiency_targets": [6900, 7100],
      "changing_interval": 200,
      "computation_interval": 50,
      "vrf": {
        "threshold_upper": "0xafff",
        "threshold_range": 80
      },
      "vdf": {
        "difficulty_max": 21,
        "difficulty_min": 16,
        "difficulty_stale": 23,
        "lambda_bound": "0x64"
      }
    }
  }
}
)";

constexpr std::string_view mainnet_json = R"({
  "node_secret": "",
  "vrf_secret": "",
  "data_path": "",
  "network_listen_ip": "0.0.0.0",
  "network_tcp_port": 10002,
  "network_transaction_interval": 100,
  "network_ideal_peer_count": 10,
  "network_max_peer_count": 50,
  "network_sync_level_size": 10,
  "network_packets_processing_threads": 14,
  "network_peer_blacklist_timeout" : 600,
  "is_light_node" : false,
  "deep_syncing_threshold" : 10,
  "network_boot_nodes": [
    {
      "id": "d063098ceca0f5ea06f9455debffe6f6d5b2efdeb179215877e356cf8154afad99f058214bd25d8198a3854a4ed8f7ef97af59b0441a7d30bc4b3918c42764ef",
      "ip": "boot-node-0.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "572778c6636361916acbc596808e1aa4e93ee0b577188f594015ec42125f58b7ec75fd59d78ca2282bc1c8c639dfc4d0eac2e57855b4fcc932c6bc6f530cd8f6",
      "ip": "boot-node-1.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "10a5108d0070559cacbb0ed368d43c98848fbc0397e9bfc1a6e7e33f15532a804d158e405657650d3ea766ed4b0d7cfcbe5867e9261deacb457da332ed1eaf2a",
      "ip": "boot-node-2.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "1dd6ae9674dee4e30f2f2f76036ad01be34bb617095b0513bc3818c8352e040fc3648fd400896fc80a544b3c23118e143928d0d49d4d575b68327f70da342939",
      "ip": "boot-node-3.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "56b74f83d3e88319cf554c6e43ca6077f7cf9594547e530582ed12196dd891b289dc7b5b4392440bcead5adbdf4e23e184b7f46940efd603c5bf0a25b36d71c6",
      "ip": "boot-node-4.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "833a3a724f5be3654524cb83307628117a668a00808fb2f34c43e5e3cb1a30354536cbdc9355172e5f285e1b4b3dde88d94385fa4df69c89da0638760ed5b0ac",
      "ip": "boot-node-5.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "94026c10fce281ede4bae9b54606703eba77cb876ddacb3eba364b7e444618d424641de206f5d5cb39f5c04da48ebad502b76d698ed341e46721c8777a8c3f15",
      "ip": "boot-node-6.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "03947eaba01564a69d6ea238f4c264ee50b34918838fee164b1b0f0de833b0098f2d4a7c05448a0f3d3aa05d55fe4d150aa3a1553fd940a433433aff8ae57a0e",
      "ip": "boot-node-7.mainnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "8a3394cccb379d66e6b7b131ef8ea9f195c333020b246135bf5d888443e8b6245cef9c90f2b6466240f38c9cfa4ccaa472b0f204623f09da819068c6d1168242",
      "ip": "boot-node-8.mainnet.taraxa.io",
      "udp_port": 10002
    }
  ],
  "rpc": {
    "http_port": 7777,
    "ws_port": 8777,
    "threads_num": 10
  },
  "max_transactions_pool_warn": 0,
  "max_transactions_pool_drop": 0,
  "max_block_queue_warn": 0,
  "db_config": {
    "db_snapshot_each_n_pbft_block": 10000,
    "db_max_snapshots": 5
  },
  "logging": {
    "configurations": [
      {
        "name": "standard",
        "on": true,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "SUMMARY",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "Taraxa_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "network",
        "on": false,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "PBFT_CHAIN",
            "verbosity": "INFO"
          },
          {
            "name": "PBFT_MGR",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "TARCAP",
            "verbosity": "DEBUG"
          },
          {
            "name": "NETWORK",
            "verbosity": "DEBUG"
          },
          {
            "name": "TRANSACTION_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAGBLKMGR",
            "verbosity": "INFO"
          },
          {
            "name": "DAGMGR",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "TaraxaNetwork_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "debug",
        "on": false,
        "verbosity": "DEBUG",
        "outputs": [
          {
            "type": "file",
            "file_name": "debug/TaraxaDebug_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      }
    ]
  },
  "chain_config": {
    "chain_id": "0x1",
    "dag_genesis_block": {
      "level": "0x0",
      "pivot": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "sig": "0xb7e22d46c1ba94d5e8347b01d137b5c428fcbbeaf0a77fb024cbbf1517656ff00d04f7f25be608c321b0d7483c402c294ff46c49b265305d046a52236c0a363701",
      "timestamp": "0x61CD9F40",
      "tips": [],
      "transactions": []
    },
    "final_chain": {
      "genesis_block_fields": {
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x61CD9F40"
      },
      "state": {
        "dpos": {
          "delegation_delay": "0x5",
          "delegation_locking_period": "0x5",
          "eligibility_balance_threshold": "0x186A0",
          "vote_eligibility_balance_step": "0x186A0",
          "validator_maximum_stake":"0x84595161401484A000000",
          "minimum_deposit":"0x0",
          "commission_change_delta":"0x0",
          "commission_change_frequency":"0x0",
          "yield_percentage":"0x14",
          "initial_validators": [
            {
              "address": "0x1f8333245650a19a0683891b7afe7787a3ce9f00",
              "owner": "0x1f8333245650a19a0683891b7afe7787a3ce9f00",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 1",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0xd4e4728bea5a67dd70dccb742bdc9c3a48465bec",
              "owner": "0xd4e4728bea5a67dd70dccb742bdc9c3a48465bec",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 2",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0xec591a85f613fe98f057dc09712a9b22cdd05845",
              "owner": "0xec591a85f613fe98f057dc09712a9b22cdd05845",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 3",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0x267e780b7843992e57f52e13018f0f97467ac06e",
              "owner": "0x267e780b7843992e57f52e13018f0f97467ac06e",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 4",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0x9d047654e55248ec38aa6723a5ab36d171008584",
              "owner": "0x9d047654e55248ec38aa6723a5ab36d171008584",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 5",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0x0d149e61cc02b5893ef6fc33bc7d67ff13eeeee0",
              "owner": "0x0d149e61cc02b5893ef6fc33bc7d67ff13eeeee0",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 6",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0x00ccd0de0809ac03fd292036ee1544185583cd88",
              "owner": "0x00ccd0de0809ac03fd292036ee1544185583cd88",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 7",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0x6f96be7626a74e86c76e65ccbccf0a38e2b62fc5",
              "owner": "0x6f96be7626a74e86c76e65ccbccf0a38e2b62fc5",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 8",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            },
            {
              "address": "0xd20131f980c9932b1df31cf3aafeecfb1d504381",
              "owner": "0xd20131f980c9932b1df31cf3aafeecfb1d504381",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa mainnet validator 9",
              "delegations": {
                "0274cfffea9fa850e54c93a23042f12a87358a82": "0x989680"
              }
            }
          ]
        },
        "eth_chain_config": {
          "byzantium_block": "0x0",
          "constantinople_block": "0x0",
          "dao_fork_block": "0xffffffffffffffff",
          "eip_150_block": "0x0",
          "eip_158_block": "0x0",
          "homestead_block": "0x0",
          "petersburg_block": "0x0"
        },
        "execution_options": {
          "disable_nonce_check": true,
          "enable_nonce_skipping": true
        },
        "block_rewards_options": {
          "disable_block_rewards": true,
          "disable_contract_distribution": true
        },
        "genesis_balances": {
          "0274cfffea9fa850e54c93a23042f12a87358a82": "0x141e8d17",
          "111f91441efc8c6c0edf6534970cc887e2fabaa8": "0x24048ce3d"
        }
      }
    },
    "gas_price" : {
      "blocks" : 200,
      "percentile" : 60
    },
    "pbft": {
      "committee_size": "0x3e8",
      "number_of_proposers": "0x14",
      "dag_blocks_size": "0xa",
      "ghost_path_move_back": "0x0",
      "lambda_ms_min": "0x5dc",
      "gas_limit": "0x3938700"
    },
    "dag": {
      "block_proposer": {
        "shard": 1,
        "transaction_limit": 250
      },
      "gas_limit": "0x989680"
    },
    "replay_protection_service": {
      "range": "0xa"
    },
    "sortition": {
      "changes_count_for_average": 10,
      "dag_efficiency_targets": [6900, 7100],
      "changing_interval": 200,
      "computation_interval": 50,
      "vrf": {
        "threshold_upper": "0xafff",
        "threshold_range": 80
      },
      "vdf": {
        "difficulty_max": 21,
        "difficulty_min": 16,
        "difficulty_stale": 23,
        "lambda_bound": "0x64"
      }
    }
  }
}
)";

constexpr std::string_view testnet_json = R"({
  "node_secret": "",
  "vrf_secret": "",
  "data_path": "",
  "network_listen_ip": "0.0.0.0",
  "network_tcp_port": 10002,
  "network_transaction_interval": 100,
  "network_ideal_peer_count": 10,
  "network_max_peer_count": 50,
  "network_sync_level_size": 10,
  "network_packets_processing_threads": 14,
  "network_peer_blacklist_timeout" : 600,
  "is_light_node" : false,
  "deep_syncing_threshold" : 10,
  "network_boot_nodes": [
    {
      "id": "f36f467529fe91a750dfdc8086fd0d2f30bad9f55a5800b6b4aa603c7787501db78dc4ac1bf3cf16e42af7c2ebb53648653013c3da1987494960d751871d598a",
      "ip": "boot-node-0.testnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "d2d445fc3276bdbf2a07628a484baabf45ccb91d6aa078a0dc3aefc11f1941899a923312ec0e664b8e57b63b774c47a006d9d1d16befd2135dcf76067736c688",
      "ip": "boot-node-1.testnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "c6e7263f44d88c0d6cc3b0d5ebdc31cf891908e8fa7e545e137d3ed0bfec1810fa24c1379228afbb53df0d59e716e17138115fd096782a84261718ab77665171",
      "ip": "boot-node-2.testnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "dcc7f60f64eee9fc470e24fd821b3d82acca646c6c951169a8f5b3de297e241cd9987e1cca1083c85b6482ba09715bbea8765710b149c55493e0bb16fc1c29cc",
      "ip": "taraxa-node-0.testnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "dedae37d9c96e0f2c8ef2796351f5560234a3e8e0407ef5cd16aaf93dd8ffd437608a585d5dc3eea54e30e1392591cfc61c6fce3cbf12b46dcc479b5fbdcde96",
      "ip": "taraxa-node-1.testnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "edc73153c2aa5991aee267f46d3ca153fa15f61eb7847b3f4c8b8fa308282b93a315a071bd5ff4327dd321faf4d979710b0e681a7088f65552ce0065fa7683fd",
      "ip": "taraxa-node-2.testnet.taraxa.io",
      "udp_port": 10002
    }
  ],
  "rpc": {
    "http_port": 7777,
    "ws_port": 8777,
    "threads_num": 10
  },
  "max_transactions_pool_warn": 0,
  "max_transactions_pool_drop": 0,
  "max_block_queue_warn": 0,
  "db_config": {
    "db_snapshot_each_n_pbft_block": 10000,
    "db_max_snapshots": 5
  },
  "logging": {
    "configurations": [
      {
        "name": "standard",
        "on": true,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "SUMMARY",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "Taraxa_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "network",
        "on": false,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "PBFT_CHAIN",
            "verbosity": "INFO"
          },
          {
            "name": "PBFT_MGR",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "TARCAP",
            "verbosity": "DEBUG"
          },
          {
            "name": "NETWORK",
            "verbosity": "DEBUG"
          },
          {
            "name": "TRANSACTION_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAGBLKMGR",
            "verbosity": "INFO"
          },
          {
            "name": "DAGMGR",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "TaraxaNetwork_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "debug",
        "on": false,
        "verbosity": "DEBUG",
        "outputs": [
          {
            "type": "file",
            "file_name": "debug/TaraxaDebug_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      }
    ]
  },
  "chain_config": {
    "chain_id": "0x2",
    "dag_genesis_block": {
      "level": "0x0",
      "pivot": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "sig": "0xb7e22d46c1ba94d5e8347b01d137b5c428fcbbeaf0a77fb024cbbf1517656ff00d04f7f25be608c321b0d7483c402c294ff46c49b265305d046a52236c0a363701",
      "timestamp": "0x62947A63",
      "tips": [],
      "transactions": []
    },
    "final_chain": {
      "genesis_block_fields": {
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x62947A63"
      },
      "state": {
        "dpos": {
          "delegation_delay": "0x5",
          "delegation_locking_period": "0x5",
          "eligibility_balance_threshold": "0xd3c21bcecceda1000000",
          "vote_eligibility_balance_step": "0x152d02c7e14af6800000",
          "validator_maximum_stake":"0x84595161401484A000000",
          "minimum_deposit":"0x0",
          "commission_change_delta":"0x0",
          "commission_change_frequency":"0x0",
          "yield_percentage":"0x14",
          "initial_validators": [
            {
              "address": "0x18551e353aa65bc0ffbdf9d93b7ad4a8fe29cf95",
              "owner": "0x18551e353aa65bc0ffbdf9d93b7ad4a8fe29cf95",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 1",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            },
            {
              "address": "0xc578bb5fc3dac3e96a8c4cb126c71d2dc9082817",
              "owner": "0xc578bb5fc3dac3e96a8c4cb126c71d2dc9082817",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 2",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x5c9afb23fba3967ca6102fb60c9949f6a38cd9e8",
              "owner": "0x5c9afb23fba3967ca6102fb60c9949f6a38cd9e8",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 3",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x403480c2b2ade0851c62bd1ff7a594c416aff7ce",
              "owner": "0x403480c2b2ade0851c62bd1ff7a594c416aff7ce",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 4",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x5042fa2711fe547e46c2f64852fdaa5982c80697",
              "owner": "0x5042fa2711fe547e46c2f64852fdaa5982c80697",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 5",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x6258d8f51ea17e873f69a2a978fe311fd95743dd",
              "owner": "0x6258d8f51ea17e873f69a2a978fe311fd95743dd",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa testnet validator 6",
              "delegations": {
                "0x76870407332398322576505f3c5423d0a71af296": "0x84595161401484a000000"
              }
            }
          ]
        },
        "eth_chain_config": {
          "byzantium_block": "0x0",
          "constantinople_block": "0x0",
          "dao_fork_block": "0xffffffffffffffff",
          "eip_150_block": "0x0",
          "eip_158_block": "0x0",
          "homestead_block": "0x0",
          "petersburg_block": "0x0"
        },
        "execution_options": {
          "disable_nonce_check": false,
          "enable_nonce_skipping": true
        },
        "block_rewards_options": {
          "disable_block_rewards": true,
          "disable_contract_distribution": true
        },
        "genesis_balances": {
          "76870407332398322576505f3c5423d0a71af296": "0x117364175f2cb0e1dfc0000",
          "f4a52b8f6dc8ab046fec6ad02e77023c044342e4": "0x1f3d8d75bcb82da15ad40000"
        }
      }
    },
    "gas_price" : {
      "blocks" : 200,
      "percentile" : 60
    },
    "pbft": {
      "committee_size": "0x3e8",
      "number_of_proposers": "0x14",
      "dag_blocks_size": "0x32",
      "ghost_path_move_back": "0x0",
      "lambda_ms_min": "0x5dc",
      "gas_limit": "0x3938700"
    },
    "dag": {
      "block_proposer": {
        "shard": 1,
        "transaction_limit": 250
      },
      "gas_limit": "0x989680"
    },
    "replay_protection_service": {
      "range": "0xa"
    },
    "sortition": {
      "changes_count_for_average": 10,
      "dag_efficiency_targets": [6900, 7100],
      "changing_interval": 200,
      "computation_interval": 50,
      "vrf": {
        "threshold_upper": "0xafff",
        "threshold_range": 90
      },
      "vdf": {
        "difficulty_max": 21,
        "difficulty_min": 16,
        "difficulty_stale": 23,
        "lambda_bound": "0x64"
      }
    }
  }
}
)";

constexpr std::string_view devnet_json = R"({
  "node_secret": "",
  "vrf_secret": "",
  "data_path": "",
  "network_listen_ip": "0.0.0.0",
  "network_tcp_port": 10002,
  "network_transaction_interval": 100,
  "network_ideal_peer_count": 15,
  "network_max_peer_count": 30,
  "network_sync_level_size": 25,
  "network_packets_processing_threads": 14,
  "network_peer_blacklist_timeout" : 600,
  "is_light_node" : false,
  "deep_syncing_threshold" : 10,
  "network_boot_nodes": [
    {
      "id": "fdcf4c860d9bb1f17608cbf2dd10ac3ae8d0ba41aa20b3e43fb85a72617a356f8609475d68b44e25dd508a0e5b36da75e7ae9aaf93360f4f002464d1d75fd353",
      "ip": "boot-node-0.devnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "5dad63f090ab5b5960dfd33b2deed974fd2e058b2af47b3d1a4682a192a47880f7b1de9aa6c80758aaabb40972a196634774373be27e0bdc52572194ad57acc2",
      "ip": "boot-node-1.devnet.taraxa.io",
      "udp_port": 10002
    },
    {
      "id": "8a919928e2ee8908d3ef7cf49f245b79d228a86fd2c1c0b8c687007e62b5777aff11e748d0b29fcebd321780ce9e0544717a4c221271252a66bd50b3db6eb532",
      "ip": "boot-node-2.devnet.taraxa.io",
      "udp_port": 10002
    }
  ],
  "rpc": {
    "http_port": 7777,
    "ws_port": 8777,
    "threads_num": 10
  },
  "max_transactions_pool_warn": 0,
  "max_transactions_pool_drop": 0,
  "max_block_queue_warn": 0,
  "db_config": {
    "db_snapshot_each_n_pbft_block": 10000,
    "db_max_snapshots": 5
  },
  "logging": {
    "configurations": [
      {
        "name": "standard",
        "on": true,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "SUMMARY",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "Taraxa_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "network",
        "on": false,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "PBFT_CHAIN",
            "verbosity": "INFO"
          },
          {
            "name": "PBFT_MGR",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "GET_DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_SYNC_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAG_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "PBFT_BLOCK_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "TARCAP",
            "verbosity": "DEBUG"
          },
          {
            "name": "NETWORK",
            "verbosity": "DEBUG"
          },
          {
            "name": "TRANSACTION_PH",
            "verbosity": "DEBUG"
          },
          {
            "name": "DAGBLKMGR",
            "verbosity": "INFO"
          },
          {
            "name": "DAGMGR",
            "verbosity": "INFO"
          }
        ],
        "outputs": [
          {
            "type": "console",
            "format": "%ThreadID% %Channel% [%TimeStamp%] %SeverityStr%: %Message%"
          },
          {
            "type": "file",
            "file_name": "TaraxaNetwork_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      },
      {
        "name": "debug",
        "on": false,
        "verbosity": "DEBUG",
        "outputs": [
          {
            "type": "file",
            "file_name": "debug/TaraxaDebug_N1_%m%d%Y_%H%M%S_%5N.log",
            "rotation_size": 10000000,
            "time_based_rotation": "0,0,0",
            "format": "%ThreadID% %ShortNodeId% %Channel% [%TimeStamp%] %SeverityStr%: %Message%",
            "max_size": 1000000000
          }
        ]
      }
    ]
  },
  "chain_config": {
    "chain_id": "0x3",
    "dag_genesis_block": {
      "level": "0x0",
      "pivot": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "sig": "0xb7e22d46c1ba94d5e8347b01d137b5c428fcbbeaf0a77fb024cbbf1517656ff00d04f7f25be608c321b0d7483c402c294ff46c49b265305d046a52236c0a363701",
      "timestamp": "0x60aee104",
      "tips": [],
      "transactions": []
    },
    "final_chain": {
      "genesis_block_fields": {
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x60aee104"
      },
      "state": {
        "dpos": {
          "delegation_delay": "0x5",
          "delegation_locking_period": "0x5",
          "eligibility_balance_threshold": "0xd3c21bcecceda1000000",
          "vote_eligibility_balance_step": "0x152d02c7e14af6800000",
          "validator_maximum_stake":"0x84595161401484A000000",
          "minimum_deposit":"0x0",
          "commission_change_delta":"0x0",
          "commission_change_frequency":"0x0",
          "yield_percentage":"0x14",
           "initial_validators": [
            {
              "address": "0x780fe8b2226cf212c55635de399ee4c2a860810c",
              "owner": "0x780fe8b2226cf212c55635de399ee4c2a860810c",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 1",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x56e0de6933d9d0453d0363caf42b136eb5854e4e",
              "owner": "0x56e0de6933d9d0453d0363caf42b136eb5854e4e",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 2",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x71bdcbec7e3642782447b0fbf31eed068dfbdbb1",
              "owner": "0x71bdcbec7e3642782447b0fbf31eed068dfbdbb1",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 3",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0xac24bc60a491bd0c29414e5f34aa6bbd8d4aa499",
              "owner": "0xac24bc60a491bd0c29414e5f34aa6bbd8d4aa499",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 5",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x635d3831ad5d1252a2a07f09b8d3539b3af34df8",
              "owner": "0x635d3831ad5d1252a2a07f09b8d3539b3af34df8",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 6",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x43af71034ed7fd0b54496a30ba4a5889a94e7088",
              "owner": "0x43af71034ed7fd0b54496a30ba4a5889a94e7088",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 7",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x4546f088bf636ed4652d1635c98ef5422805dfa3",
              "owner": "0x4546f088bf636ed4652d1635c98ef5422805dfa3",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 8",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x8ca042649a263272442bee8b7209fa19426e54c4",
              "owner": "0x8ca042649a263272442bee8b7209fa19426e54c4",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 9",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x7d7319df8950546850a01a0d793ee602f6eb390f",
              "owner": "0x7d7319df8950546850a01a0d793ee602f6eb390f",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 10",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x64c171b9845c15c4555f7a4489895f0e687c496c",
              "owner": "0x64c171b9845c15c4555f7a4489895f0e687c496c",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 11",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x614c85fad6f17f03949f735e05b1a24c5155b726",
              "owner": "0x614c85fad6f17f03949f735e05b1a24c5155b726",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 12",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0xeff3dd2b0a6c29146c46ca01764aae0691ee1744",
              "owner": "0xeff3dd2b0a6c29146c46ca01764aae0691ee1744",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 13",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0xe543a20db4fa1820cc9f00144fc402bb1f31aa29",
              "owner": "0xe543a20db4fa1820cc9f00144fc402bb1f31aa29",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 14",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x211a5ec33fec843b14319bcd62ab30c2a064745e",
              "owner": "0x211a5ec33fec843b14319bcd62ab30c2a064745e",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 15",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x5354adf587cad5fe74e4912d4b6c1f754538891d",
              "owner": "0x5354adf587cad5fe74e4912d4b6c1f754538891d",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 16",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x1473a6c154655fdc1f19d98e5823d3bb3f09a895",
              "owner": "0x1473a6c154655fdc1f19d98e5823d3bb3f09a895",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 17",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x9588f6457d67792f141424983a93978f44331054",
              "owner": "0x9588f6457d67792f141424983a93978f44331054",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 18",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0xb48da366e19f141f5647dcdb0960eb88719e1c8d",
              "owner": "0xb48da366e19f141f5647dcdb0960eb88719e1c8d",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 19",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            },
            {
              "address": "0x2b95aeed70a4e21fcb8665b1a1e16eb114a1caf3",
              "owner": "0x2b95aeed70a4e21fcb8665b1a1e16eb114a1caf3",
              "commission": 0,
              "endpoint": "",
              "description": "Taraxa devnet validator 20",
              "delegations": {
                "0x7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x84595161401484a000000"
              }
            }
          ]
        },
        "eth_chain_config": {
          "byzantium_block": "0x0",
          "constantinople_block": "0x0",
          "dao_fork_block": "0xffffffffffffffff",
          "eip_150_block": "0x0",
          "eip_158_block": "0x0",
          "homestead_block": "0x0",
          "petersburg_block": "0x0"
        },
        "execution_options": {
          "disable_nonce_check": false,
          "enable_nonce_skipping": true
        },
        "block_rewards_options": {
          "disable_block_rewards": false,
          "disable_contract_distribution": false
        },
        "genesis_balances": {
          "2cd4da7d3b345e022ca7e997c2bb3276a4d3d2e9": "0x1027e72f1f12813088000000",
          "7e4aa664f71de4e9d0b4a6473d796372639bdcde": "0x1027e72f1f12813088000000"
        }
      }
    },
    "gas_price" : {
      "blocks" : 200,
      "percentile" : 60
    },
    "pbft": {
      "committee_size": "0x3e8",
      "number_of_proposers": "0x14",
      "dag_blocks_size": "0x32",
      "ghost_path_move_back": "0x0",
      "lambda_ms_min": "0x29a",
      "gas_limit": "0x3938700"
    },
    "dag": {
      "block_proposer": {
        "shard": 1,
        "transaction_limit": 250
      },
      "gas_limit": "0x989680"
    },
    "replay_protection_service": {
      "range": "0xa"
    },
    "sortition": {
      "changes_count_for_average": 10,
      "dag_efficiency_targets": [6900, 7100],
      "changing_interval": 200,
      "computation_interval": 50,
      "vrf": {
        "threshold_upper": "0xafff",
        "threshold_range": 80
      },
      "vdf": {
        "difficulty_max": 21,
        "difficulty_min": 16,
        "difficulty_stale": 23,
        "lambda_bound": "0x64"
      }
    }
  }
}
)";

}  // namespace taraxa::cli
// DO NOT EDIT !!!
// THIS FILE IS GENERATED BY CMAKE
